spring.application.name=Proyecto_Lenguajes

spring.datasource.url=jdbc:mysql://localhost:3306/lenguajes_2025
spring.datasource.username=root
spring.datasource.password=00000000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.show-sql=true
