# Nombre del proyecto
spring.application.name=Proyecto_Lenguajes

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/lenguajes_2025
spring.datasource.username=root
spring.datasource.password=00000000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update        
spring.jpa.show-sql=true                      
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false                 

# Formato de consola más limpio
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Codificación y zona horaria (opcional, pero útil)
spring.datasource.hikari.connection-init-sql=SET time_zone = '-06:00'
spring.sql.init.encoding=UTF-8
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
